services:
  backend:
    build: 
      context: ./Backend/Backend
    ports:
      - 5000:8080
    volumes:
      - ./data:/app/data
    depends_on:
      - sqlite-web

  frontend:
    build:
      context: ./Frontend
    ports:
      - 3000:5173 
    environment:
      - VITE_API_URL=http://localhost:5000
    command: npm run dev -- --host
    depends_on:
      - backend

  sqlite-web:
    image: coleifer/sqlite-web
    container_name: sqlite-web-view
    ports:
      - 8081:8080   
    volumes:
      - ./data:/data
    command: ["sqlite_web", "/data/pii.db", "--host", "0.0.0.0"]